"""create telegram message states

Revision ID: 8aca55acbd12
Revises: 
Create Date: 2026-09-27 14:16:28.134535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aca55acbd12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_message_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('django_message_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('reply_markup', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('django_message_id')
    )
    op.create_index(op.f('ix_telegram_message_states_chat_id'), 'telegram_message_states', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_message_states_chat_id'), table_name='telegram_message_states')
    op.drop_table('telegram_message_states')
    # ### end Alembic commands ###
